/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/$slug': typeof EventsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/events/$slug'
    | '/programs/$slug'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/events/$slug'
    | '/programs/$slug'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/products'
    | '/sitemap.xml'
    | '/events/$slug'
    | '/programs/$slug'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
